name: Hello World!!
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        default: 'World'
jobs:
  hello-world:
    runs-on: ubuntu-22.04
    steps:
      - name: print hello message
        run: echo "Hello GitHub Actions!!"

