name: massai mara park 01 gradle build
on:
  workflow_dispatch

jobs:
  mmpark01_gradle_build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          push: false
          load: true
          tags: massai-mara:v1
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Docker container
        run: |
          docker run -d --name mmpark01 -p 8080:8080 massai-mara:v1
          sleep 20
          docker ps
          docker logs mmpark01

      - name: run automated test #1 (root endpoint)
        run: |
          curl http://localhost:8080 || exit 1
          sleep 5 # wait 5 seconds

      - name: run automated test #2 (/images endpoint)
        run: |
          curl http://localhost:8080/images || exit 1
          sleep 5 # wait 5 seconds

      - name: run automated test #3 (/animal endpoint)
        run: |
          curl http://localhost:8080/animal || exit 1
          sleep 5 # wait 5 seconds
