name: massai mara park 01 compose build
on:
  workflow_dispatch

jobs:
  mmpark01_compose_build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: checkout docker-compose version
        run: docker-compose --version

      - name: build with docker-compose
        run: docker compose build

      - name: run with docker-compose
        run: |
          docker compose up -d
          sleep 30 # wait 30 seconds

          docker compose ps
          docker compose logs

      - name: run automated test #1 (root endpoint)
        run: |
          curl http://localhost:8080 || exit 1
          sleep 5 # wait 5 seconds

      - name: run automated test #2 (/images endpoint)
        run: |
          curl http://localhost:8080/images || exit 1
          sleep 5 # wait 5 seconds

      - name: run automated test #3 (/animal endpoint)
        run: |
          curl http://localhost:8080/animal || exit 1
          sleep 5 # wait 5 seconds
