name: massai mara park 05 build
on:
  workflow_dispatch

jobs:
  mmpark01_compose_build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/massai_mara:v1 .
          docker push ${{ secrets.DOCKER_USERNAME }}/massai_mara:v1

      - name: Logout from Docker Hub
        if: always()
        run: docker logout
