name: massai mara park 01 multiple jobs
on:
  workflow_dispatch

jobs:
  build:
    name: build JAR
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: grant execute permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: list build/libs directory
        run: ls -al ./build/libs

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: application.jar
          path: build/libs/*SNAPSHOT.jar

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: run springboot application
        run: |
            java -jar build/libs/massai-mara-park-0.0.1-SNAPSHOT.jar & || exit 1
            sleep 30 # stand by 30sec

  test:
    name: app test
    needs: deploy
    runs-on: ubuntu-22.04
    steps:
      - name: run automated test #1
        run: |
            curl http://localhost:8080 || exit 1
            sleep 5 # stand by 5sec

      - name: run automated test #1
        run: |
            curl http://localhost:8080/images || exit 1
            sleep 5 # stand by 5sec

      - name: run automated test #1
        run: |
            curl http://localhost:8080/animal || exit 1
            sleep 5 # stand by 5 sec